from .color_analysis import get_representative_color, weighted_median, analyze_hue_range
from .color_masks import crear_imagen_canal_color
from .position import detectar_posicion, compute_detect_radius
from .visualization import crear_overlay_canal, plot_diagnostico_canal, generar_diagnostico_mascaras
from .pipeline import detectar_canal_con_imagen_separada, procesar_imagen_completa
